import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import { isMSWEnabled } from '@/utils/isMSWEnabled'

import { MSWProvider } from './msw-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Server-side MSW setup for production builds (E2E testing)
if (process.env.NEXT_RUNTIME === 'nodejs' && isMSWEnabled()) {
  const { server } = require('../../mocks/server')
  server.listen({ onUnhandledRequest: 'bypass' })
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  )
}
